# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "TP Blog"
description: > # this means to ignore newlines until "email:"
   A blog about technology, IT, development, books, reviews & not only

email: tassospan@outlook.com
#blog logo
logo: "/assets/images/tp_logo.jpg"
# blog cover
cover: "/assets/images/mycover.jpg"

name: 'Tassos P.'
author: 'Tassos P.'
author_image: "/assets/images/author_tp.jpg"

paginate:	5

url: "https://tassospan.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@_TassosP_'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/_TassosP_
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/el.don.anastasio
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/tassospan
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
